### ISSUE TITLE
AEB model question

### ISSUE THREAD

**Issue by Druscilar** [clarky104/carla_aebs#3]
Hello, I appreciate your work.
You provided the code for emergency braking RL training; how long did it take you to complete the training process?
Is it possible to share your trained model for the emergency braking?

**Comment by ethanmclark1** [comment]
I cannot remember, it was a while ago now - if I were to guess I would say it was somewhere between 6-12 hours.

If you're stuck, these videos ([1](https://youtu.be/MynOPIJi4VY?si=JY0RK-DyOEEZfn71), [2](https://youtu.be/J1F32aVSYaU?si=xW7RE7inlqASF6mC)) were quite helpful for me.

**Comment by Druscilar** [comment]
Hello

I have had several attempts at trying to run the aeb model but failed.
What town did you populate it in and also the simulator keeps crashing
cause the agents aren't destroyed in the episodes can you help with that.
Thanks
