### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by susankbart** [clarky104/carla_aebs#4]
Hello, 
Thank you for the resources provided.
I am inquiring about the lane follower model you provided, Did you train it on the data from the simulator?
Also, did you publish your work, I would like to take a look at the documentation if possible.

Thank you.

**Comment by ethanmclark1** [comment]
Yes, both the lane follower and the braking system were trained on the data from the CARLA simulator. Also, I didn't publish a paper for this, all information relating to the code is in the GitHub.
